service: listen-api
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function
  - serverless-step-functions
  - serverless-export-env

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  name: vishal
  stage: ${opt:stage, self:provider.stage}
  logRetentionInDays: 30
  logLevel:
    default: ALL
    prod: ERROR

  appSyncLogLevel:
    default: ALL
    prod: ERROR

  AssetsBucket:
    Name: ${cf:nomadmethod-api-${self:provider.stage}.AssetsBucketName}
    Arn: ${cf:nomadmethod-api-${self:provider.stage}.AssetsBucketArn}
  ContentsTable:
    Name: ${cf:nomadmethod-api-${self:provider.stage}.ContentsTableName}
  CharactersTable:
    Name: ${cf:nomadmethod-api-${self:provider.stage}.CharactersTableName}
  ComponentsTable:
    Name: ${cf:nomadmethod-api-${self:provider.stage}.ComponentsTableName}
  UserCredentialsTable:
    Name: ${cf:nomadmethod-api-${self:provider.stage}.UserCredentialsTableName}
  MandarinoKMSKey:
    Arn: ${cf:nomadmethod-api-${self:provider.stage}.MandarinoKMSKeyArn}

  CognitoUserPool:
    Arn: ${cf:nomadmethod-api-${self:provider.stage}.CognitoUserPoolArn}
    Id: ${cf:nomadmethod-api-${self:provider.stage}.CognitoUserPoolId}
    ProviderName: ${cf:nomadmethod-api-${self:provider.stage}.CognitoUserPoolProviderName}

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  region: us-east-1
  memorySize: 512
  eventBridge:
    useCloudFormation: true
  environment:
    # kms_arn: !GetAtt ComposeKMSKey.Arn
    serviceName: ${self:service}
    stage: ${self:provider.stage}
    STAGE: ${self:provider.stage}
    LOG_LEVEL: ${self:custom.logLevel.${self:provider.stage}, self:custom.logLevel.default}
    USER_CREDENTIALS_TABLE: ${self:custom.UserCredentialsTable.Name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:ListTables
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - ApiGateway:*
      Resource: "*"
    - Effect: Allow
      Action:
        - cloudformation:ValidateTemplate
        - cloudformation:CreateStack
        - cloudformation:ListStackResources
        - cloudformation:DescribeStackResource
        - cloudformation:DescribeStacks
      Resource: "*"
      # Email
    - Effect: Allow
      Action: ses:SendEmail
      Resource: "*"
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: "*"

    - Effect: Allow
      Action: events:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: "*"

functions:
  add-translations:
    timeout: 300
    handler: functions/listen/add-translations.handler
    environment:
      MEDIA_TABLE: !Ref MediaTable
      MEDIA_FILES_TABLE: !Ref MediaFilesTable
      MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt MediaTable.StreamArn

  get-media:
    handler: functions/listen/get-media.handler
    events:
      - http:
          path: /v1/get-media
          method: POST
          cors: true
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.CognitoUserPool.Arn}
    environment:
      MEDIA_TABLE: !Ref MediaTable
      MEDIA_FILES_TABLE: !Ref MediaFilesTable
      MEDIA_ASSETS_BUCKET: ${self:custom.AssetsBucket.Name}
      # MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket

  list-medias:
    handler: functions/listen/list-medias.handler
    events:
      - http:
          path: /v1/list-medias
          method: POST
          cors: true
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.CognitoUserPool.Arn}
    environment:
      MEDIA_TABLE: !Ref MediaTable
      MEDIA_FILES_TABLE: !Ref MediaFilesTable
      MEDIA_ASSETS_BUCKET: ${self:custom.AssetsBucket.Name}
      # MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket

  add-media:
    handler: functions/listen/add-media.handler
    events:
      - http:
          path: /v1/add-media
          method: POST
          cors: true
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.CognitoUserPool.Arn}
    environment:
      MEDIA_TABLE: !Ref MediaTable
      MEDIA_FILES_TABLE: !Ref MediaFilesTable
      MEDIA_ASSETS_BUCKET: ${self:custom.AssetsBucket.Name}
      # MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket
  get-upload-url:
    handler: functions/media/get-upload-url.handler
    events:
      - http:
          path: /v1/get-upload-url
          method: POST
          cors: true
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.CognitoUserPool.Arn}
    environment:
      MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
        Resource: !Sub ${MediaAssetsBucket.Arn}/*
  get-presigned-url:
    handler: functions/media/get-presigned-url.handler
    events:
      - http:
          path: /v1/get-presigned-url
          method: POST
          cors: true
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.CognitoUserPool.Arn}
    environment:
      MEDIA_ASSETS_BUCKET: !Ref MediaAssetsBucket
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: !Sub ${MediaAssetsBucket.Arn}/*

resources:
  Resources:
    MediaAssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccelerateConfiguration:
          AccelerationStatus: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
    MediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: byUserId
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Tags:
          # To keep track of user table for diffeent environment
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: media-table
    MediaFilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: byUserId
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Tags:
          # To keep track of user table for diffeent environment
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: media-files-table
